#!/usr/bin/env bash
# Generates ~/.config/tmux/current-theme.conf from the active theme's colors.toml.
# Linux: reads omarchy's current theme (~/.config/omarchy/current/theme.name)
# Mac:   reads ~/.config/theme.name (written by install.sh, editable by user)
# Falls back to matte-black if no theme file or colors.toml is found.

OUT="$HOME/.config/tmux/current-theme.conf"
PL_RIGHT=$''
PL_LEFT=$''
SEP=$''

theme=""
colors=""

if [[ "$(uname)" == "Linux" ]]; then
  omarchy_theme="$HOME/.config/omarchy/current/theme.name"
  [[ -f "$omarchy_theme" ]] && theme=$(tr -d '[:space:]' < "$omarchy_theme")
fi

if [[ -z "$theme" ]]; then
  user_theme="$HOME/.config/theme.name"
  [[ -f "$user_theme" ]] && theme=$(tr -d '[:space:]' < "$user_theme")
fi

if [[ -n "$theme" ]]; then
  for dir in \
    "$HOME/.local/share/omarchy/themes/$theme" \
    "$HOME/.config/themes/$theme"; do
    if [[ -f "$dir/colors.toml" ]]; then
      colors="$dir/colors.toml"
      break
    fi
  done
fi

if [[ -n "$colors" ]]; then
  get() { grep "^$1 " "$colors" | sed 's/.*= *"\(.*\)"/\1/'; }
  bg=$(get background)
  fg=$(get foreground)
  accent=$(get accent)
  subtle=$(get color8)
  error=$(get color1)
  success=$(get color2)
  yellow=$(get color3)
  teal=$(get color6)
  mid=$(get color12)
  bright=$(get color14)
else
  theme="matte-black"
  bg="#121212"
  fg="#bebebe"
  accent="#e68e0d"
  subtle="#8a8a8d"
  error="#D35F5F"
  success="#FFC107"
  yellow="#b91c1c"
  teal="#bebebe"
  mid="#f59e0b"
  bright="#eaeaea"
fi

# --- Generate lsd theme ---
LSD_THEME_OUT="$HOME/.config/lsd/colors.yaml"
mkdir -p "$HOME/.config/lsd"

hex_to_rgb() {
  local hex="${1#\#}"
  echo "[$(( 16#${hex:0:2} )), $(( 16#${hex:2:2} )), $(( 16#${hex:4:2} ))]"
}

# r;g;b format for LS_COLORS truecolor entries
hex_to_ls() {
  local hex="${1#\#}"
  printf '%d;%d;%d' "$(( 16#${hex:0:2} ))" "$(( 16#${hex:2:2} ))" "$(( 16#${hex:4:2} ))"
}

cat > "$LSD_THEME_OUT" << LSDEOF
user:
  rgb: $(hex_to_rgb "$subtle")
group:
  rgb: $(hex_to_rgb "$subtle")
permission:
  read:
    rgb: $(hex_to_rgb "$success")
  write:
    rgb: $(hex_to_rgb "$yellow")
  exec:
    rgb: $(hex_to_rgb "$error")
  exec-sticky:
    rgb: $(hex_to_rgb "$accent")
  no-access:
    rgb: $(hex_to_rgb "$subtle")
  octal:
    rgb: $(hex_to_rgb "$bright")
  acl:
    rgb: $(hex_to_rgb "$teal")
  context:
    rgb: $(hex_to_rgb "$fg")
date:
  hour-old:
    rgb: $(hex_to_rgb "$fg")
  day-old:
    rgb: $(hex_to_rgb "$mid")
  older:
    rgb: $(hex_to_rgb "$subtle")
size:
  none:
    rgb: $(hex_to_rgb "$subtle")
  small:
    rgb: $(hex_to_rgb "$fg")
  medium:
    rgb: $(hex_to_rgb "$mid")
  large:
    rgb: $(hex_to_rgb "$error")
inode:
  valid:
    rgb: $(hex_to_rgb "$teal")
  invalid:
    rgb: $(hex_to_rgb "$subtle")
links:
  valid:
    rgb: $(hex_to_rgb "$teal")
  invalid:
    rgb: $(hex_to_rgb "$error")
tree-edge:
  rgb: $(hex_to_rgb "$subtle")
git-status:
  default:
    rgb: $(hex_to_rgb "$subtle")
  unmodified:
    rgb: $(hex_to_rgb "$subtle")
  ignored:
    rgb: $(hex_to_rgb "$subtle")
  new-in-index:
    rgb: $(hex_to_rgb "$success")
  new-in-workdir:
    rgb: $(hex_to_rgb "$success")
  typechange:
    rgb: $(hex_to_rgb "$mid")
  deleted:
    rgb: $(hex_to_rgb "$error")
  renamed:
    rgb: $(hex_to_rgb "$teal")
  modified:
    rgb: $(hex_to_rgb "$yellow")
  conflicted:
    rgb: $(hex_to_rgb "$error")
LSDEOF

# LS_COLORS: dirs, symlinks, executables, file types
# Each type gets a distinct palette slot
cat > "$HOME/.config/ls-colors.sh" << LSEOF
export LS_COLORS="di=1;38;2;$(hex_to_ls "$accent"):ln=38;2;$(hex_to_ls "$teal");4:ex=38;2;$(hex_to_ls "$success"):or=38;2;$(hex_to_ls "$error");4:fi=38;2;$(hex_to_ls "$fg"):*.md=38;2;$(hex_to_ls "$accent"):*.txt=38;2;$(hex_to_ls "$fg"):*.sh=38;2;$(hex_to_ls "$success"):*.lua=38;2;$(hex_to_ls "$mid"):*.py=38;2;$(hex_to_ls "$mid"):*.js=38;2;$(hex_to_ls "$mid"):*.ts=38;2;$(hex_to_ls "$mid"):*.rs=38;2;$(hex_to_ls "$mid"):*.go=38;2;$(hex_to_ls "$mid"):*.json=38;2;$(hex_to_ls "$yellow"):*.yaml=38;2;$(hex_to_ls "$yellow"):*.yml=38;2;$(hex_to_ls "$yellow"):*.toml=38;2;$(hex_to_ls "$yellow")"
LSEOF

# --- Generate starship config ---
STARSHIP_BASE="$HOME/.config/starship/starship.base.toml"
STARSHIP_OUT="$HOME/.config/starship.toml"

if [[ -f "$STARSHIP_BASE" ]]; then
  sed \
    -e "s/__ACCENT__/${accent}/g" \
    -e "s/__FG__/${fg}/g" \
    -e "s/__BG__/${bg}/g" \
    -e "s/__SUBTLE__/${subtle}/g" \
    -e "s/__ERROR__/${error}/g" \
    -e "s/__SUCCESS__/${success}/g" \
    "$STARSHIP_BASE" > "$STARSHIP_OUT"
fi

# --- Generate tmux config ---
cat > "$OUT" << EOF
# Auto-generated by apply-theme.sh from theme: $theme — do not edit manually
set -g status-style                "bg=${bg},fg=${fg}"
set -g pane-border-style           "fg=${subtle}"
set -g pane-active-border-style    "fg=${accent}"
set -g message-style               "bg=${accent},fg=${bg}"
set -g mode-style                  "bg=${accent},fg=${bg}"

set -g status-left  "#[bg=${accent},fg=${bg},bold] #{session_name} #[bg=${bg},fg=${accent},nobold]${PL_RIGHT} "
set -g status-right "#[bg=${bg},fg=${subtle}]${PL_LEFT}#[bg=${subtle},fg=${fg}] %H:%M "
set -g window-status-format         "#[bg=${bg},fg=${fg}] #{window_index} #{window_name} "
set -g window-status-current-format "#[bg=${bg},fg=${accent},bold] #{window_index} #{window_name} ●#[nobold] "
set -g window-status-separator      "#[bg=${bg},fg=${subtle}]${SEP}"
set -g window-status-current-style  ""
set -g window-status-style          ""
EOF
