#!/usr/bin/env bash
# Generates ~/.config/tmux/current-theme.conf from the active theme's colors.toml.
# Linux: reads omarchy's current theme (~/.config/omarchy/current/theme.name)
# Mac:   reads ~/.config/theme.name (written by install.sh, editable by user)
# Falls back to matte-black if no theme file or colors.toml is found.

OUT="$HOME/.config/tmux/current-theme.conf"
PL_RIGHT=$''
PL_LEFT=$''
SEP=$''

theme=""
colors=""

if [[ "$(uname)" == "Linux" ]]; then
  omarchy_theme="$HOME/.config/omarchy/current/theme.name"
  [[ -f "$omarchy_theme" ]] && theme=$(tr -d '[:space:]' < "$omarchy_theme")
fi

if [[ -z "$theme" ]]; then
  user_theme="$HOME/.config/theme.name"
  [[ -f "$user_theme" ]] && theme=$(tr -d '[:space:]' < "$user_theme")
fi

if [[ -n "$theme" ]]; then
  for dir in \
    "$HOME/.local/share/omarchy/themes/$theme" \
    "$HOME/.config/themes/$theme"; do
    if [[ -f "$dir/colors.toml" ]]; then
      colors="$dir/colors.toml"
      break
    fi
  done
fi

if [[ -n "$colors" ]]; then
  get() { grep "^$1 " "$colors" | sed 's/.*= *"\(.*\)"/\1/'; }
  bg=$(get background)
  fg=$(get foreground)
  accent=$(get accent)
  subtle=$(get color8)
  error=$(get color1)
  success=$(get color2)
else
  theme="matte-black"
  bg="#121212"
  fg="#bebebe"
  accent="#e68e0d"
  subtle="#8a8a8d"
  error="#D35F5F"
  success="#FFC107"
fi

# --- Generate starship config ---
STARSHIP_BASE="$HOME/.config/starship/starship.base.toml"
STARSHIP_OUT="$HOME/.config/starship.toml"

if [[ -f "$STARSHIP_BASE" ]]; then
  sed \
    -e "s/__ACCENT__/${accent}/g" \
    -e "s/__FG__/${fg}/g" \
    -e "s/__BG__/${bg}/g" \
    -e "s/__SUBTLE__/${subtle}/g" \
    -e "s/__ERROR__/${error}/g" \
    -e "s/__SUCCESS__/${success}/g" \
    "$STARSHIP_BASE" > "$STARSHIP_OUT"
fi

# --- Generate tmux config ---
cat > "$OUT" << EOF
# Auto-generated by apply-theme.sh from theme: $theme — do not edit manually
set -g status-style                "bg=${bg},fg=${fg}"
set -g pane-border-style           "fg=${subtle}"
set -g pane-active-border-style    "fg=${accent}"
set -g message-style               "bg=${accent},fg=${bg}"
set -g mode-style                  "bg=${accent},fg=${bg}"

set -g status-left  "#[bg=${accent},fg=${bg},bold] #{session_name} #[bg=${bg},fg=${accent},nobold]${PL_RIGHT} "
set -g status-right "#[bg=${bg},fg=${subtle}]${PL_LEFT}#[bg=${subtle},fg=${fg}] %H:%M "
set -g window-status-format         "#[bg=${bg},fg=${fg}] #{window_index} #{window_name} "
set -g window-status-current-format "#[bg=${bg},fg=${accent},bold] #{window_index} #{window_name} ●#[nobold] "
set -g window-status-separator      "#[bg=${bg},fg=${subtle}]${SEP}"
set -g window-status-current-style  ""
set -g window-status-style          ""
EOF
