#------------------------------------------------------------------------------#
#                                  Workspace Rules                             #
#------------------------------------------------------------------------------#
# workspace = 1, monitor:DP-2, default:true
# workspace = 2, monitor:DP-2 
# workspace = 3, monitor:DP-2 
# workspace = 4, monitor:DP-2 
# workspace = 5, monitor:DP-2 
# 
# workspace = 6, monitor:DP-1
# workspace = 7, monitor:DP-1
# workspace = 8, monitor:DP-1 
# workspace = 9, monitor:DP-1 
# workspace = 10, monitor:DP-1,default:true

# special_scale_factor = 1
workspace = special:magic, gapsin:30, gapsout:75, shadow:true
workspace = special:test, gapsin:30, gapsout:75, shadow:true
exec-once = [workspace special:magic silent] slack
exec-once = [workspace special:magic silent] brave --app=https://teams.microsoft.com/v2/
# exec-once = [workspace 2 silent] brave --app=https://outlook.office.com/mail/
workspace = 10, on-created-empty: brave --app=https://outlook.office.com/mail/
