#------------------------------------------------------------------------------#
#                                  Workspace Rules                             #
#------------------------------------------------------------------------------#
# workspace = 1, monitor:DP-2, default:true
# workspace = 2, monitor:DP-2 
# workspace = 3, monitor:DP-2 
# workspace = 4, monitor:DP-2 
# workspace = 5, monitor:DP-2 
# 
# workspace = 6, monitor:DP-1
# workspace = 7, monitor:DP-1
# workspace = 8, monitor:DP-1 
# workspace = 9, monitor:DP-1 
# workspace = 10, monitor:DP-1,default:true

# special_scale_factor = 1
workspace = special:mail, gapsin:30, gapsout:75, shadow:true
workspace = special:teams, gapsin:30, gapsout:75, shadow:true
workspace = special:slack, gapsin:30, gapsout:75, shadow:true
workspace = special:scratchpad, gapsin:30, gapsout:75, shadow:true

# workspace = special:scratchpad, on-created-empty: brave 
#
# for some reason this doesn't open 
workspace = special:teams, on-created-empty: outlook-for-linux
workspace = special:teams, on-created-empty: teams-for-linux
workspace = special:slack, on-created-empty: slack
